In [2]:
import numpy as np

In [3]:
#list vs numpy 
#slow vs fast less memory
#plotting(MATPLOTLIB), mathemathics(MATLAB), backend ,ML

In [4]:
#store all sort of data i.e 1darray, 2darray, 3darray

### The Basics

In [5]:
a = np.array([1,2,3], dtype='int16')
print(a)
#int32 or int16 is size how much to take

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension

b.ndim

2

In [8]:
# Get Dimension
a.ndim

1

In [9]:
# Get Shape
a.shape

(3,)

In [10]:
# Get Shape
b.shape

(2, 3)

In [11]:
# Get Type
a.dtype

dtype('int16')

In [12]:
# Get Size
a.itemsize

2

In [13]:
# Get total size
a.nbytes

6

In [14]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Get a specific element [r, c]
a[1, 5]

13

In [17]:
# Get a specific row 
a[-1, 2:]

array([10, 11, 12, 13, 14])

In [18]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [19]:
# Getting a little more fancy [row,startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [21]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element (work outside in)
b[0,1,1]

4

In [23]:
# replace same dimension
b[:,1,:] = [[9,9,9],[8,8,]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
b

### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

In [ ]:
# Any other number
np.full((2,2), 99)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)


In [ ]:
# Random decimal numbers
np.random.random_sample(a.shape)

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

In [ ]:
# The identity matrix/sqaure matrix
np.identity(5)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

##### Be careful when copying arrays!!!

In [25]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [35]:
a ** 2

array([ 1,  4,  9, 16])

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) #matrix_multiple

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c) #linear_algebra_determinant

1.0

In [41]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.min(stats)

1

In [44]:
np.max(stats, axis=1)

array([3, 6])

In [45]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [66]:
import numpy as np
import os

# Option 1: Use raw string (r prefix) to prevent escape character interpretation
filedata = np.genfromtxt(r'C:\Users\Asus\Downloads\data.txt', delimiter=',')

# Option 2: Use forward slashes instead of backslashes
# filedata = np.genfromtxt('C:/Users/Asus/Downloads/data.txt', delimiter=',')

# Option 3: Use double backslashes to escape the backslash
# filedata = np.genfromtxt('C:\\Users\\Asus\\Downloads\\data.txt', delimiter=',')

# Print current working directory to check where Python is looking for the file
print("Current working directory:", os.getcwd())

filedata = filedata.astype('int32')
print(filedata)  # load data from text file

Current working directory: C:\Users\Asus\Downloads
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [82]:
(~((filedata > 50) & (filedata < 100))) #~ is for not sign

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [83]:
(((filedata > 50) & (filedata < 100))) 

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [84]:
filedata[filedata > 150 ]

array([196, 766, 999])

In [85]:
f_d = np.any(filedata > 150, axis=0)
print(f_d)

# Count True and False
count_true = np.count_nonzero(f_d)
count_false = f_d.size - count_true

print("True count:", count_true)
print("False count:", count_false)

[False False False False  True False False False False False False False
 False False False False False False]
True count: 1
False count: 17
